import Ext from '../web_extension'
import { randomHex } from './hmac_sha256'

// The key content scripts use to sign window.postMessage requests to each
// other (cs_postmessage.js). Generated by the background, handed to content
// scripts over runtime messaging (CS_CHANNEL_KEY in ipc_bg_cs.js) — a path no
// web page can observe or call.
//
// Kept in chrome.storage.session for the same reason as the ipc session id
// (ipc_cache.ts): a woken service worker must hand out the key the live
// content scripts already hold, and a reload/update or browser restart, which
// ends every content script, starts a fresh one. Default access level, so
// only extension contexts can read it. Without storage.session (neither
// supported target lacks it) the key lives in memory and a worker restart
// changes it; frames loaded before then can no longer reach frames loaded
// after until they reload.
const storageKey = 'cs_channel_key'

let keyPromise: Promise<string> | null = null

function sessionArea (): any {
  const area = (Ext as any)?.storage?.session
  return area && typeof area.get === 'function' && typeof area.set === 'function' ? area : null
}

export function ensureChannelKey (): Promise<string> {
  if (keyPromise) return keyPromise

  const p = (async () => {
    const area = sessionArea()

    if (area) {
      const stored = await Promise.resolve(area.get(storageKey)).catch(() => null)
      const key    = stored && stored[storageKey]
      if (typeof key === 'string' && key) return key
    }

    const key = randomHex(32)
    if (area) await Promise.resolve(area.set({ [storageKey]: key })).catch(() => {})
    return key
  })()

  p.catch(() => { if (keyPromise === p) keyPromise = null })
  keyPromise = p
  return p
}
